### ISSUE TITLE
better experiment-end mechanism

### ISSUE THREAD

**Issue by LeanderK** [coolcrowd/object-service#161]
the function is located in resources and gets called from QualityIdentificator, which is a bit strange. But the main problem is, that it can get called more than once per experiment, resulting in multiple events etc.

NinjaEdit by marcelhollerbach:
So the complete problem described a bit bigger:
- The 2 hours sleep results in a restcall which does not answer in 2 hours.
- The experimentstate is not changed before the sleep, which means you can submit 2 more hours answers and ratings
- ExperimentEnd is called all the time a new answer is there, without checking if this is valid or if the experiment is already finished.
- if the os crashes in those two hours, recover! make sure the experiment is payed!
- You are just emitting the experiment how it was two hours before. BAD read the object new from the database.

**Comment by lckr** [comment]
Wating for #184

**Comment by LeanderK** [comment]
#184 introduces a new state, shutdown. It should be used for the experiment-end state

**Comment by LeanderK** [comment]
you can create a new branch based on db-update and start working there

**Comment by marcelhollerbach** [comment]
So the complete problem described a bit bigger:
- The 2 hours sleep results in a restcall which does not answer in 2 hours.
- The experimentstate is not changed before the sleep, which means you can submit 2 more hours answers and ratings
- ExperimentEnd is called all the time a new answer is there, without checking if this is valid or if the experiment is already finished.
- if the os crashes in those two hours, recover! make sure the experiment is payed!

**Comment by lckr** [comment]
Amusing how much things can grow overnight.
As far as a know the third point is desired. While the platforms are unpublished, it only holds a certain timewindow(2h) open, so that workers still being in the assignment can complete their task,
Of course we can just remove that behavior

**Comment by lckr** [comment]
The remaining points are:
- crash-prevention / recovery
- improvement of waiting-state

Do you agree @marcelhollerbach

**Comment by marcelhollerbach** [comment]
You wrote there a TODO when you wrote the code, the ticket here is open since 10 days. Trying to run the code (only once) would have shown you that a restrequest will be blocked for 2 hours. You really cannot call this "overnight". 
You are right the third thing is done by purpose, but really this should not result in another thread waiting for 2 hours, no even in scheudle the experiment end again.

**Comment by marcelhollerbach** [comment]
The weak points are:
- Saving the state of the experiment, making sure the experiment is in the right state (shutdown)
- on start make sure all experiments are scheuduled again with the correct times (in absolutly no case the payment stuff should be called before less than 2 hours of waiting)
- NEVER end a experiment more than twice.
- Stop blocking rest calls! This is deadlocking the os since the complete spark-java stuff will wait there 2 hours.
- After the two hours of waiting, get the new state from the database, do not only hack on with the old state

**Comment by lckr** [comment]
The ticket didn't touch the silly 2h-waiting until recently. And I have to admit that I didn't feel like the creator of this fragile section as it arouse our funny merge-night in the infobau :>

**Comment by marcelhollerbach** [comment]
git blame tells something else. 
Not only for this solution.
Also for the time where is was done as a event.

**Comment by lckr** [comment]
#204 solves
